#ifndef ERROR_H
	#define ERROR_H

	#define INCORRECT_BASE 101
	#define MEMORY_ALLOCATE_ERROR 102
	#define UNKNOWN_FLAG 103
	#define TOO_MANY_ARGS 104
	#define NOT_ENOUGH_ARGS 105
	#define OPEN_FILE_ERROR 106
	#define INCORRECT_ARG 107
	#define NULL_POINTER 108

#endif 
