#ifndef ERROR_H
#define ERROR_H

#define OK 0
#define INCORRECT_BASE 101
#define MEMORY_ALLOCATE_ERROR 102
#define UNKNOWN_FLAG 103
#define TOO_MANY_ARGS 104
#define NOT_ENOUGH_ARGS 105
#define OPEN_FILE_ERROR 106
#define INCORRECT_ARG 107
#define NULL_POINTER 108
#define INDEX_OUT_OF_BORDERS 109
#define BAD_DIVISION 110
#define EMPTY_FILE 111
#define KEY_NOT_FOUND 112
#define VALUE_ALREADY_EXISTS 113
#define OBJECT_IS_EMPTY 114
#define UNKNOWN_SYMBOL 115


// MATH ERRORS //

#define BALANCE_OF_PARENTHESIS_IS_BROKEN 2001

#endif 
